import Head from "next/head";

import AboutAlamer from "../components/home/AboutAlamer";
import Department from "../components/home/Department";
import Hero from "../components/home/Hero";
import MallInNumbers from "../components/home/MallInNumbers";
import Partners from "../components/home/Partners";
import OurNew from "../components/home/OurNew";

export default function Home({ currentDir }) {
  return (
    <>
      <Head>
        <title>العامر مول</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <MallInNumbers currentDir={currentDir} />
      <AboutAlamer currentDir={currentDir} />
      <Department currentDir={currentDir} />
      <Partners currentDir={currentDir} />
      <OurNew currentDir={currentDir} />
    </>
  );
}
